---
- name: Create pods using deployment 
  hosts: kubernetes 
  # become: true
  user: ubuntu
 
  tasks: 
  - name: create a deployment
    command: kubectl apply -f valaxy-deploy.yml

  - name: update deployment with new pods if image updated in docker hub
    ## when we execute these command our old pod gets stopped and pull latest image | cuz we have given pullpolicy always in deployment file it pull latest image and start new container | comment need 1.15 kubectl up or hight version then it works
    command: kubectl rollout restart deployment.v1.apps/valaxy-deployment
